name: 'Ansible CI/CD'
on:
  push:
    paths:
      - 'task02/**'
  pull_request:
    paths:
      - 'task02/**'

jobs:
  ansible:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: task02
    steps:
      - uses: actions/checkout@v4

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Check Playbook (Dry Run)
        run: ansible-playbook -i inventory.ini playbook.yml --check

      - name: Run Playbook
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: ansible-playbook -i inventory.ini playbook.yml
        env:
          ANSIBLE_PRIVATE_KEY_FILE: ${{ secrets.SSH_KEY }}
